apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostname-lb-edge
  labels:
    app: hostname-lb-edge
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hostname-lb-edge
  template:
    metadata:
      labels:
        app: hostname-lb-edge
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: node-role.kubernetes.io/edge
                  operator: Exists
                - key: node-role.kubernetes.io/agent
                  operator: Exists
      containers:
        - name: hostname
          image: poorunga/serve_hostname:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9376
---
apiVersion: v1
kind: Service
metadata:
  name: hostname-lb-svc
spec:
  selector:
    app: hostname-lb-edge
  ports:
    - name: http-0
      port: 12345
      protocol: TCP
      targetPort: 9376
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: edgemesh-gateway
spec:
  selector:
    kubeedge: edgemesh-gateway
  servers:
    - hosts:
        - '*'
      port:
        name: http-0
        number: 23333
        protocol: HTTP
      tls:
        cipherSuites:
          - 'TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA'
          - 'TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384'
          - 'TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256'
          - 'TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA'
          - 'TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256'
          - 'TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384'
          - 'TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA'
          - 'TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA'
          - 'TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256'
          - 'TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256'
        credentialName: gw-secret
        maxProtocolVersion: TLSV1_2
        minProtocolVersion: TLSV1_2
        mode: MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: hostname-lb-svc
spec:
  host: hostname-lb-edge
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: edgemesh-gateway-svc
spec:
  gateways:
    - edgemesh-gateway
  hosts:
    - '*'
  http:
    - match:
      - uri:
          prefix: /
      route:
      - destination:
          host: hostname-lb-svc
          port:
            number: 12345
