apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-https
spec:
  selector:
    matchLabels:
      run: nginx-https
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx-https
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 443
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: secret-volume
        - mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          name: configmap-volume
      volumes:
      - name: secret-volume
        secret:
          secretName: nginxsecret
      - name: configmap-volume
        configMap:
          name: nginxconfigmap
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-https
  labels:
    run: nginx-https
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    run: nginx-https
